services:
  cash_register.db:
    image: postgres:15-alpine
    container_name: cash_register_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Dev_StrongPass!2026
      - POSTGRES_DB=CashRegister_Db
    ports:
      - "5432:5432"
    volumes:
      - db_cash_register:/var/lib/postgresql/data
    networks:
      - cash_register-network

networks:
  cash_register-network:
    driver: bridge

volumes:
  db_cash_register: